# Universidad Autonoma de Aguascalientes
## Centro de Ciencias Basicas
## Departamento de Ciencias de la Computación
## Materia: Machine Learning y Deep Learning
## Profesor: Dr. Francisco Javier Luna Rosas
### Alumno: Carlos Daniel Torres Macías
### Perido: Enero - Junio 2026

#### Practica 16 Implemente en Python Componentes Matemáticos del Deep Learning

#### Paso 1: Importar las librerias necesarias

In [1]:
import numpy as np

#### Paso 2: Escalares - Tensores 0D
#### Un escalar es un solo numero. Es un tensor de 0 dimensiones (0D). En Python, un escalar se puede representar como un número simple.

In [2]:
x = np.array(2)
x

array(2)

#### Paso 3: Vectores - Tensores 1D
#### Un vector es una lista de números. Es un tensor de 1 dimensión (1D). En Python, un vector se puede representar como una lista o un array de una sola dimensión.

In [4]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

#### Paso 4: Matrices - Tensores 2D
#### Una matriz es una tabla de números con filas y columnas. Es un tensor de 2 dimensiones (2D). En Python, una matriz se puede representar como una lista de listas o un array de dos dimensiones.

In [7]:
x = np.array([[7, 80, 4, 38, 2],
              [4, 77, 1, 33, 3],
              [5, 78, 2, 34, 1]])
x

array([[ 7, 80,  4, 38,  2],
       [ 4, 77,  1, 33,  3],
       [ 5, 78,  2, 34,  1]])

#### Paso 5: Tensores 3D y superiores
#### Un tensor de 3 dimensiones (3D) es una colección de matrices. En Python, un tensor de 3D se puede representar como una lista de listas de listas o un array de tres dimensiones. Los tensores de dimensiones superiores siguen el mismo patrón, con cada dimensión adicional representando una nueva "capa" de datos.

In [9]:
x = np.array([[[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]]])
x

array([[[ 7, 80,  4, 38,  2],
        [ 4, 77,  1, 33,  3],
        [ 5, 78,  2, 34,  1]],

       [[ 7, 80,  4, 38,  2],
        [ 4, 77,  1, 33,  3],
        [ 5, 78,  2, 34,  1]],

       [[ 7, 80,  4, 38,  2],
        [ 4, 77,  1, 33,  3],
        [ 5, 78,  2, 34,  1]]])

#### Paso 6: Tensores 4D y superiores
#### Un tensor de 4 dimensiones (4D) es una colección de tensores de 3D. En Python, un tensor de 4D se puede representar como una lista de listas de listas de listas o un array de cuatro dimensiones. Los tensores de dimensiones superiores siguen el mismo patrón, con cada dimensión adicional representando una nueva "capa" de datos.

In [10]:
x = np.array([[[[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]]],
              [[[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]],
              [[7, 80, 4, 38, 2], [4, 77, 1, 33, 3], [5, 78, 2, 34, 1]]]])
x

array([[[[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]],

        [[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]],

        [[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]]],


       [[[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]],

        [[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]],

        [[ 7, 80,  4, 38,  2],
         [ 4, 77,  1, 33,  3],
         [ 5, 78,  2, 34,  1]]]])

In [12]:
x.ndim

4

#### Conclusión
#### En esta práctica, hemos implementado en Python los componentes matemáticos fundamentales del Deep Learning, incluyendo escalares, vectores, matrices y tensores de diversas dimensiones. Estos conceptos son esenciales para comprender cómo funcionan las redes neuronales y cómo se procesan los datos en el contexto del aprendizaje profundo.

#### Referencias
#### - Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.
#### - Chollet, F. (2017). Deep Learning with Python. Manning Publications.
#### - NumPy Documentation: https://numpy.org/doc/